package com.education.tutoring.management.repository.jpa.service;

import com.education.tutoring.management.application.port.out.PasswordService;
import lombok.AllArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

/**
 * Spring Security-based implementation of the {@link PasswordService} output port. Acts
 * as a security adapter, delegating cryptographic operations (hashing and verification)
 * to the underlying {@link PasswordEncoder}. This ensures secure credential management
 * while keeping the core domain entirely decoupled from framework-specific security
 * libraries.
 */
@Service
@AllArgsConstructor
public class PasswordServiceImpl implements PasswordService {

	private final PasswordEncoder passwordEncoder;

	/**
	 * Securely hashes a raw plaintext password using the underlying Spring Security
	 * {@link PasswordEncoder}.
	 * @param rawPassword the plaintext password to be hashed
	 * @return the resulting cryptographic hash generated by the encoder
	 */
	@Override
	public String encode(String rawPassword) {
		return passwordEncoder.encode(rawPassword);
	}

	/**
	 * Verifies whether a raw plaintext password matches a previously encoded password
	 * hash by delegating the comparison to the underlying {@link PasswordEncoder}.
	 * @param rawPassword the plaintext password provided by the user
	 * @param encodedPassword the stored cryptographic hash to compare against
	 * @return {@code true} if the raw password matches the encoded hash, {@code false}
	 * otherwise
	 */
	@Override
	public boolean matches(String rawPassword, String encodedPassword) {
		return passwordEncoder.matches(rawPassword, encodedPassword);
	}

}
